CDRIVER-3954 Run all integration tests in Versioned API evergreen tests (#787)
* CDRIVER-3917 route all test client and client_pool creation through the test framework

* small fixes

* add missing include

* rename pool method to match client method

* Refactor test framework client factories to accept API version

* Revert change in mongoc-cache.c

Despite the #include, the linker does not like this:
tests/test-mongoc-cache.c.o: In function `ping':
src/libmongoc/tests/test-mongoc-cache.c:45: undefined reference to `test_framework_client_new'

* Run all tests with requireApiVersion=true

* Fix large_ismaster test

* Don't set server api when client can't be created

* Don't use test clients in tests specifically testing server API behaviour

* Print default API version in test output

* Set requireApiVersion option earlier

* Consider apiVersion field when assembling large bulk operation

* Fix wrong comment wording

Co-authored-by: Benjamin Rewis <32186188+benjirewis@users.noreply.github.com>

* Fix inaccurate variable name

* Remove obsolete todo

* Document MONGODB_API_VERSION environment variable in contributing docs

* Document new test methods

* Fix tests with acceptApiVersion2

* Update newly added test

Co-authored-by: samantharitter <samantha.ritter@10gen.com>
Co-authored-by: Benjamin Rewis <32186188+benjirewis@users.noreply.github.com>